<?php

// Route file auto generated by owl-admin, don't modify it manually.

use Slowlyo\OwlAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // 账本记录
    $router->resource('account', \App\Admin\Controllers\AccountController::class);

});